export const API_ERROR_CODES = {
  MISSING_API_KEY: 'MISSING_API_KEY',
  INVALID_API_KEY: 'INVALID_API_KEY',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  WAREHOUSE_NOT_FOUND: 'WAREHOUSE_NOT_FOUND',
  INVENTORY_LOT_NOT_FOUND: 'INVENTORY_LOT_NOT_FOUND',
  PRODUCT_ALREADY_EXISTS: 'PRODUCT_ALREADY_EXISTS',
  WAREHOUSE_ALREADY_EXISTS: 'WAREHOUSE_ALREADY_EXISTS',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  UNIT_COST_REQUIRED: 'UNIT_COST_REQUIRED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
